version: '3.8'

services:
  commerciq:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../outputs:/app/outputs
      - ../data/external:/app/data/external
      - ../data/processed:/app/data/processed
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped